version: '3.8'

services:
  db:
    image: mysql:8
    container_name: caroarena-db
    environment:
      MYSQL_ROOT_PASSWORD: dat123
      MYSQL_DATABASE: pbl4_be
    ports:
      - "1444:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: hoangdat1612/caroarena-app
    container_name: caroarena-app
    ports:
      - "5999:5999"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/pbl4_be?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dat123
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: