version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: carogame
      MYSQL_USER: yourusername
      MYSQL_PASSWORD: yourpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  app:
    image: pbl4_be_latest1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/carogame
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword
    depends_on:
      - db
    ports:
      - "8080:8080"